version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./container/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
 
  app:
    build:
      context: .
      dockerfile: ./container/rails/Dockerfile
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  web:
    build:
      context: .
      dockerfile: ./container/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./src:/app
